### ISSUE TITLE
crash on fabric server

### ISSUE THREAD

**Issue by Trinsdar** [Carbon-Config-Project/CarbonConfig#10]
seems adding configs via the method in Carbon config causes a crash on fabric servers, saying it cannot load LocalPlayer in environment type SERVER
```
[20:28:51] [main/ERROR] (Minecraft) Failed to start the minecraft server
 java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'carbonconfig'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [minecraft-project-@fabric-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219) [architectury-transformer-5.2.80-runtime.jar:5.2.80]
	Suppressed: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class carbonconfiglib.CarbonConfig
		at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:15) ~[kubejs-fabric-1802.5.1-build.329.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
		at net.minecraft.server.Main.main(Main.java:101) [minecraft-project-@fabric-merged-named.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
		at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
		at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219) [architectury-transformer-5.2.80-runtime.jar:5.2.80]
	Caused by: java.lang.NoClassDefFoundError: Could not initialize class carbonconfiglib.CarbonConfig
		at muramasa.antimatter.util.fabric.AntimatterPlatformUtilsImpl.createConfig(AntimatterPlatformUtilsImpl.java:231) ~[AntimatterAPI-fabric-0.2-1.18.2-dev.jar:?]
		at muramasa.antimatter.util.AntimatterPlatformUtils.createConfig(AntimatterPlatformUtils.java) ~[AntimatterAPI-common-0.2-1.18.2-dev.jar:?]
		at muramasa.gregtech.GregTechConfig.createConfig(GregTechConfig.java:30) ~[gti-common-0.2-1.18.2-dev.jar:?]
		at muramasa.gregtech.GregTech.onRegistrarInit(GregTech.java:66) ~[gti-common-0.2-1.18.2-dev.jar:?]
		at muramasa.antimatter.fabric.AntimatterImpl.lambda$initialize$0(AntimatterImpl.java:59) ~[AntimatterAPI-fabric-0.2-1.18.2-dev.jar:?]
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
		at muramasa.antimatter.fabric.AntimatterImpl.initialize(AntimatterImpl.java:59) ~[AntimatterAPI-fabric-0.2-1.18.2-dev.jar:?]
		at muramasa.antimatter.integration.kubejs.fabric.AntimatterKubeJSImpl.onRegister(AntimatterKubeJSImpl.java:7) ~[AntimatterAPI-fabric-0.2-1.18.2-dev.jar:?]
		at muramasa.antimatter.integration.kubejs.AntimatterKubeJS.onRegister(AntimatterKubeJS.java) ~[AntimatterAPI-common-0.2-1.18.2-dev.jar:?]
		at muramasa.antimatter.integration.kubejs.AntimatterKubeJS.initStartup(AntimatterKubeJS.java:17) ~[AntimatterAPI-common-0.2-1.18.2-dev.jar:?]
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
		at dev.latvian.mods.kubejs.util.KubeJSPlugins.forEachPlugin(KubeJSPlugins.java:83) ~[kubejs-fabric-1802.5.1-build.329.jar:?]
		at dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:117) ~[kubejs-fabric-1802.5.1-build.329.jar:?]
		at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:12) ~[kubejs-fabric-1802.5.1-build.329.jar:?]
		... 9 more
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Cannot load class net.minecraft.client.player.LocalPlayer in environment type SERVER [in thread "main"]
		at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
		at carbonconfiglib.CarbonConfig.<clinit>(CarbonConfig.java:64) ~[carbon-config-pjhTjv8N.jar:?]
		at java.lang.Class.forName0(Native Method) ~[?:?]
		at java.lang.Class.forName(Class.java:467) ~[?:?]
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.19.jar:?]
		... 9 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class carbonconfiglib.CarbonConfig
		at tesseract.fabric.TesseractImpl.createConfig(TesseractImpl.java:107) ~[TesseractAPI-fabric-0.2.2-1.18.2-dev.jar:?]
		at tesseract.Tesseract.createConfig(Tesseract.java) ~[TesseractAPI-0.2.2-1.18.2-dev.jar:?]
		at tesseract.TesseractConfig.createConfig(TesseractConfig.java:23) ~[TesseractAPI-0.2.2-1.18.2-dev.jar:?]
		at tesseract.Tesseract.init(Tesseract.java:37) ~[TesseractAPI-0.2.2-1.18.2-dev.jar:?]
		at tesseract.fabric.TesseractImpl.onInitialize(TesseractImpl.java:75) ~[TesseractAPI-fabric-0.2.2-1.18.2-dev.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
		at net.minecraft.server.Main.main(Main.java:101) [minecraft-project-@fabric-merged-named.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
		at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
		at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219) [architectury-transformer-5.2.80-runtime.jar:5.2.80]
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Cannot load class net.minecraft.client.player.LocalPlayer in environment type SERVER [in thread "main"]
		at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
		at carbonconfiglib.CarbonConfig.<clinit>(CarbonConfig.java:64) ~[carbon-config-pjhTjv8N.jar:?]
		at java.lang.Class.forName0(Native Method) ~[?:?]
		at java.lang.Class.forName(Class.java:467) ~[?:?]
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.19.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.19.jar:?]
		... 9 more
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Cannot load class net.minecraft.client.player.LocalPlayer in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at carbonconfiglib.CarbonConfig.<clinit>(CarbonConfig.java:64) ~[carbon-config-pjhTjv8N.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 8 more```

**Comment by Speiger** [comment]
Fixed in dev on friday
