### ISSUE TITLE
runData caues crash in dev

### ISSUE THREAD

**Issue by Trinsdar** [Carbon-Config-Project/CarbonConfig#8]
seems using runData can cause a null pointer exception from the minecraft instance being null
```
Caused by: java.lang.NullPointerException: Cannot read field "player" because the return value of "net.minecraft.client.Minecraft.getInstance()" is null
	at carbonconfiglib.networking.CarbonNetwork.getClientPlayer(CarbonNetwork.java:110) ~[carbon-config-VrESRvWV.jar%23184!/:1.19.2-1.1.1]
	at carbonconfiglib.networking.CarbonNetwork.isInWorld(CarbonNetwork.java:100) ~[carbon-config-VrESRvWV.jar%23184!/:1.19.2-1.1.1]
	at carbonconfiglib.impl.internal.EventHandler.onConfigChanged(EventHandler.java:106) ~[carbon-config-VrESRvWV.jar%23184!/:1.19.2-1.1.1]
	at carbonconfiglib.config.FileSystemWatcher.onConfigChanged(FileSystemWatcher.java:163) ~[carbon-config-VrESRvWV.jar%23184!/:1.19.2-1.1.1]
	at carbonconfiglib.config.ConfigHandler.save(ConfigHandler.java:362) ~[carbon-config-VrESRvWV.jar%23184!/:1.19.2-1.1.1]
	at carbonconfiglib.config.ConfigHandler.load(ConfigHandler.java:189) ~[carbon-config-VrESRvWV.jar%23184!/:1.19.2-1.1.1]
	at carbonconfiglib.config.ConfigHandler.register(ConfigHandler.java:161) ~[carbon-config-VrESRvWV.jar%23184!/:1.19.2-1.1.1]
	at trinsdar.ic2c_extras.Ic2cExtrasConfig.createConfig(Ic2cExtrasConfig.java:33) ~[%23179!/:?]
	at trinsdar.ic2c_extras.IC2CExtras.<init>(IC2CExtras.java:36) ~[%23179!/:?]```

**Comment by Speiger** [comment]
will be addressed in tomorrows patch :)
